// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: api/proto/tracklite.proto

package tracklite

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LocationUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                             // UNIX timestamp
	BatteryLevel  float32                `protobuf:"fixed32,5,opt,name=battery_level,json=batteryLevel,proto3" json:"battery_level,omitempty"`  // %
	SignalQuality string                 `protobuf:"bytes,6,opt,name=signal_quality,json=signalQuality,proto3" json:"signal_quality,omitempty"` // "3G", "4G", "5G", "WiFi"
	GpsAccuracy   float32                `protobuf:"fixed32,7,opt,name=gps_accuracy,json=gpsAccuracy,proto3" json:"gps_accuracy,omitempty"`     // meters
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationUpdate) Reset() {
	*x = LocationUpdate{}
	mi := &file_api_proto_tracklite_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationUpdate) ProtoMessage() {}

func (x *LocationUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tracklite_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationUpdate.ProtoReflect.Descriptor instead.
func (*LocationUpdate) Descriptor() ([]byte, []int) {
	return file_api_proto_tracklite_proto_rawDescGZIP(), []int{0}
}

func (x *LocationUpdate) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *LocationUpdate) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *LocationUpdate) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *LocationUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LocationUpdate) GetBatteryLevel() float32 {
	if x != nil {
		return x.BatteryLevel
	}
	return 0
}

func (x *LocationUpdate) GetSignalQuality() string {
	if x != nil {
		return x.SignalQuality
	}
	return ""
}

func (x *LocationUpdate) GetGpsAccuracy() float32 {
	if x != nil {
		return x.GpsAccuracy
	}
	return 0
}

type LocationUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationUpdateResponse) Reset() {
	*x = LocationUpdateResponse{}
	mi := &file_api_proto_tracklite_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationUpdateResponse) ProtoMessage() {}

func (x *LocationUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tracklite_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationUpdateResponse.ProtoReflect.Descriptor instead.
func (*LocationUpdateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_tracklite_proto_rawDescGZIP(), []int{1}
}

func (x *LocationUpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LocationUpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_tracklite_proto protoreflect.FileDescriptor

const file_api_proto_tracklite_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/tracklite.proto\x12\ttracklite\"\xf4\x01\n" +
	"\x0eLocationUpdate\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12#\n" +
	"\rbattery_level\x18\x05 \x01(\x02R\fbatteryLevel\x12%\n" +
	"\x0esignal_quality\x18\x06 \x01(\tR\rsignalQuality\x12!\n" +
	"\fgps_accuracy\x18\a \x01(\x02R\vgpsAccuracy\"L\n" +
	"\x16LocationUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2^\n" +
	"\x0eTrackerService\x12L\n" +
	"\fSendLocation\x12\x19.tracklite.LocationUpdate\x1a!.tracklite.LocationUpdateResponseB9Z7github.com/lucasdellasala/tracklite/api/proto;trackliteb\x06proto3"

var (
	file_api_proto_tracklite_proto_rawDescOnce sync.Once
	file_api_proto_tracklite_proto_rawDescData []byte
)

func file_api_proto_tracklite_proto_rawDescGZIP() []byte {
	file_api_proto_tracklite_proto_rawDescOnce.Do(func() {
		file_api_proto_tracklite_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_tracklite_proto_rawDesc), len(file_api_proto_tracklite_proto_rawDesc)))
	})
	return file_api_proto_tracklite_proto_rawDescData
}

var file_api_proto_tracklite_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_tracklite_proto_goTypes = []any{
	(*LocationUpdate)(nil),         // 0: tracklite.LocationUpdate
	(*LocationUpdateResponse)(nil), // 1: tracklite.LocationUpdateResponse
}
var file_api_proto_tracklite_proto_depIdxs = []int32{
	0, // 0: tracklite.TrackerService.SendLocation:input_type -> tracklite.LocationUpdate
	1, // 1: tracklite.TrackerService.SendLocation:output_type -> tracklite.LocationUpdateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_tracklite_proto_init() }
func file_api_proto_tracklite_proto_init() {
	if File_api_proto_tracklite_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_tracklite_proto_rawDesc), len(file_api_proto_tracklite_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_tracklite_proto_goTypes,
		DependencyIndexes: file_api_proto_tracklite_proto_depIdxs,
		MessageInfos:      file_api_proto_tracklite_proto_msgTypes,
	}.Build()
	File_api_proto_tracklite_proto = out.File
	file_api_proto_tracklite_proto_goTypes = nil
	file_api_proto_tracklite_proto_depIdxs = nil
}
